export const SET_LOADING = 'SET_LOADING';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_CURRENT_GROUP = 'SET_CURRENT_GROUP';
export const GET_GROUPS = 'GET_GROUPS';
export const ADD_GROUP = 'ADD_GROUP';
export const CLEAR_GROUPS = 'CLEAR_GROUPS';
export const CLEAR_CURRENT_GROUP = 'CLEAR_CURRENT_GROUP';
export const FIND_GROUP = 'FIND_GROUP';
export const CLEAR_GROUP_SEARCH_RESULTS = 'CLEAR_GROUP_SEARCH_RESULTS';
export const GROUPS_ERROR = 'GROUPS_ERRORS';

export const SEARCH = 'SEARCH';
export const SET_CURRENT_RESULT = 'SET_CURRENT_RESULT'
export const CLEAR_RESULTS = 'CLEAR_RESULTS';
export const SEARCH_ERROR = 'SEARCH_ERROR';

export const GET_RECORDS = 'GET_RECORDS';
export const ADD_RECORD = 'ADD_RECORD';
export const SET_CURRENT_RECORD = 'SET_CURRENT_RECORD';
export const RECORDS_ERROR = 'RECORDS_ERROR';

export const GET_POSTS = 'GET_POSTS';
export const ADD_POST = 'ADD_POST';
export const SET_CURRENT_POST = 'SET_CURRENT_POST';
export const POSTS_ERROR = 'POSTS_ERROR';

export const ADD_COMMENT = 'ADD_COMMENT';
export const GET_RECORD_COMMENTS = 'GET_RECORD_COMMENTS';
export const COMMENT_ERROR = 'COMMENT_ERROR';

export const GET_MARKERS = 'GET_MARKERS';
export const ADD_MARKER = 'ADD_MARKER';
export const MARKERS_ERROR = 'MARKERS_ERROR';

export const GET_BOOKMARKS = 'GET_BOOKMARKS';
export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const BOOKMARKS_ERROR = 'BOOKMARKS_ERROR';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';