// Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_LOADING = 'SET_LOADING';
export const UPLOAD_SUCCESS = 'UPLOAD_PICTURE';
export const UPLOAD_FAIL = 'UPLOAD_FAIL';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

// Groups
export const SET_CURRENT_GROUP = 'SET_CURRENT_GROUP';
export const GET_GROUPS = 'GET_GROUPS';
export const ADD_GROUP = 'ADD_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const CLEAR_GROUPS = 'CLEAR_GROUPS';
export const CLEAR_CURRENT_GROUP = 'CLEAR_CURRENT_GROUP';
export const FIND_GROUP = 'FIND_GROUP';
export const CLEAR_GROUP_SEARCH_RESULTS = 'CLEAR_GROUP_SEARCH_RESULTS';
export const GROUPS_ERROR = 'GROUPS_ERRORS';
export const LOADING_GROUPS = 'LOADING_GROUPS';
export const ADD_MEMBER = 'ADD_MEMBER';
export const DECLINE_REQUEST = 'DECLINE_REQUEST';
export const LEAVE_GROUP = 'LEAVE_GROUP';

// Search
export const SEARCH = 'SEARCH';
export const SET_CURRENT_RESULT = 'SET_CURRENT_RESULT'
export const CLEAR_RESULTS = 'CLEAR_RESULTS';
export const CLEAR_CURRENT_RESULT = 'CLEAR_CURRENT_RESULT';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const RESULTS_LOADING = 'RESULTS_LOADING';

// Records
export const GET_RECORDS = 'GET_RECORDS';
export const ADD_RECORD = 'ADD_RECORD';
export const DELETE_RECORD = 'DELETE_RECORD';
export const SET_CURRENT_RECORD = 'SET_CURRENT_RECORD';
export const CLEAR_RECORDS = 'CLEAR_RECORDS';
export const CLEAR_CURRENT_RECORD = 'CLEAR_CURRENT_RECORD';
export const RECORDS_ERROR = 'RECORDS_ERROR';
export const LOADING_RECORDS = 'LOADING_RECORDS';

// Posts
export const GET_POSTS = 'GET_POSTS';
export const ADD_POST = 'ADD_POST';
export const CLEAR_POSTS = 'CLEAR_POSTS';
export const POSTS_ERROR = 'POSTS_ERROR';
export const DELETE_POST = 'DELETE_POST';
export const LOADING_POSTS = 'LOADING_POSTS';

// Comments
export const COMMENT_ERROR = 'COMMENT_ERROR';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';

// Markers
export const GET_MARKERS = 'GET_MARKERS';
export const ADD_MARKER = 'ADD_MARKER';
export const CLEAR_MARKERS = 'CLEAR_MARKERS';
export const MARKERS_ERROR = 'MARKERS_ERROR';
export const LOADING_MARKERS = 'LOADING_MARKERS'
export const DELETE_MARKER = 'DELETE_MARKER';

// Bookmarks
export const GET_BOOKMARKS = 'GET_BOOKMARKS';
export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const CLEAR_BOOKMARKS = 'CLEAR_BOOKMARKS';
export const BOOKMARKS_ERROR = 'BOOKMARKS_ERROR';
export const LOADING_BOOKMARKS = 'LOADING_BOOKMARKS';
export const DELETE_BOOKMARK = 'DELETE_BOOKMARK';

// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Modals
export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSED = 'MODAL_CLOSED';